spring.application.name=cineplay
spring.config.import=optional:classpath:.env[.properties]
spring.datasource.url=jdbc:mysql://localhost:3306/cineplay
spring.datasource.username=${ENV_MYSQL_USER}
spring.datasource.password=${ENV_MYSQL_PASSWORD}
